//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultaLlamadas.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CatalogoAcceso
    {
        public int PersonId { get; set; }

        [Display(Name = "Nombre")]

        public string PersonName { get; set; }

        [Required (ErrorMessage ="El usuario es requerido")]
        [Display(Name ="Usuario")]
        public string UserName { get; set; }

        [Required(ErrorMessage = "La contraseña es requerida")]
        [Display(Name = "Contraseña")]
        [DataType(DataType.Password)] 
        public string Password { get; set; }
      

        [Display(Name = "Tipo de usuario")]

        public string UserType { get; set; }


        public string Rol { get; set; }
        
        public string ErrorMessage { get; set; }
    }
}
